Repository milvus-io/milvus-sdk-go, pull requests merged in 2021-08, with the labels that each got.

#171 Add CreateCollectionByRow
  client/client.go
  client/client_grpc_collection_test.go
  client/client_grpc_row.go
  client/client_grpc_row_test.go
  client/client_test.go
Labels: lgtm, approved, ci-passed, size/XL

#173 Hide Connect method
  client/client.go
  client/client_grpc_collection.go
Labels: lgtm, approved, size/S, ci-passed

#174 Add API documents markdown
  docs/README.md
  docs/create_collection.md
  docs/create_index.md
  docs/create_partition.md
  docs/describe_collection.md
  docs/describe_index.md
  docs/drop_collection.md
  docs/drop_index.md
  docs/drop_partition.md
  docs/flush.md
  docs/get_index_build_progress.md
  docs/has_partition.md
  docs/insert.md
  docs/list_collections.md
  docs/load_collection.md
  docs/load_partitions.md
  docs/new_client.md
  docs/release_collection.md
  docs/release_partitions.md
  docs/search.md
  docs/show_partitions.md
Labels: documentation, lgtm, approved, ci-passed, size/XL

#175 [skip ci] revise api reference
  docs/README.md
  docs/create_collection.md
  docs/create_index.md
  docs/create_partition.md
  docs/describe_collection.md
  docs/describe_index.md
  docs/drop_collection.md
  docs/drop_index.md
  docs/drop_partition.md
  docs/flush.md
  docs/get_index_build_progress.md
  docs/has_partition.md
  docs/insert.md
  docs/list_collections.md
  docs/load_collection.md
  docs/load_partitions.md
  docs/new_client.md
  docs/release_collection.md
  docs/release_partitions.md
  docs/search.md
  docs/show_partitions.md
Labels: ci-passed, size/L

#177 Fix examples link
  README.md
Labels: approved, size/XS

#186 Fix master coverage not triggered
  .github/workflows/main.yml
Labels: enhancement, lgtm, approved, ci-passed, size/XS

#188 Update mergify, compulsory related issue
  .github/mergify.yml
Labels: enhancement, lgtm, approved, size/S, ci-passed
