Repository milvus-io/milvus-sdk-go, pull requests merged in 2021-09, with the labels that each got.

#189 [skip ci] Create Index Parameter Range Template
  docs/index_limitations.md
Labels: lgtm, approved, ci-passed, size/L

#194 Respect context deadline when doing sync wait
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_partition.go
  client/client_grpc_partition_test.go
Labels: lgtm, approved, ci-passed, size/L

#196 [skip ci] Update Go SDK contributing guide
  CONTRIBUTING.md
Labels: lgtm, approved, ci-passed, size/M

#195 Typo fix
  docs/index_limitations.md
Labels: lgtm, approved, ci-passed, size/XS, do-not-merge/missing-related-issue

#198 [skip ci] Add Milvus x Hacktoberfest banner
  README.md
Labels: lgtm, approved, ci-passed, size/XS, do-not-merge/missing-related-issue

#200 [skip ci] PR with kind/improvement label can bypass need-issue rule
  .github/mergify.yml
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement
