Repository milvus-io/milvus-sdk-go, pull requests merged in 2021-07, with the labels that each got.

#122 Add case for create collection
  client/client_grpc_dd_test.go
Labels: approved, ci-passed, size/S, test/ut

#123 Add mergify config yml
  .github/mergify.yml
  .github/workflows/main.yml
Labels: approved, size/M

#124 Add entity package unit tests
  client/client_grpc_dd_test.go
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_bool.go
  entity/columns_bool_test.go
  entity/columns_double.go
  entity/columns_double_test.go
  entity/columns_float.go
  entity/columns_float_test.go
  entity/columns_floatvector.go
  entity/columns_floatvector_test.go
  entity/columns_int16.go
  entity/columns_int16_test.go
  entity/columns_int32.go
  entity/columns_int32_test.go
  entity/columns_int64.go
  entity/columns_int64_test.go
  entity/columns_int8.go
  entity/columns_int8_test.go
  entity/columns_string.go
  entity/columns_string_test.go
  entity/columns_test.go
  entity/gen/gen.go
  entity/index.go
  entity/index_test.go
  entity/schema_test.go
  entity/segment_test.go
  scripts/run_go_unittest.sh
Labels: approved, ci-passed, lgtm, size/XXL

#128 Add mergify badge
  README.md
Labels: approved, ci-passed, lgtm, size/XS

#129 Unify client param signature
  client/client.go
  client/client_grpc_dd.go
  client/client_grpc_dd_test.go
  client/client_mock_test.go
Labels: approved, ci-passed, lgtm, size/S

#130 Add basic example and examples menu
  examples/README.md
  examples/basic/basic.go
Labels: approved, ci-passed, lgtm, size/L

#132 Add ValueByIdx for scalar columns
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_bool.go
  entity/columns_bool_test.go
  entity/columns_double.go
  entity/columns_double_test.go
  entity/columns_float.go
  entity/columns_float_test.go
  entity/columns_floatvector.go
  entity/columns_floatvector_test.go
  entity/columns_int16.go
  entity/columns_int16_test.go
  entity/columns_int32.go
  entity/columns_int32_test.go
  entity/columns_int64.go
  entity/columns_int64_test.go
  entity/columns_int8.go
  entity/columns_int8_test.go
  entity/columns_string.go
  entity/columns_string_test.go
  entity/gen/gen.go
Labels: approved, ci-passed, lgtm, size/L

#135 Add collection check
  client/client_grpc_dd.go
  client/client_grpc_dd_test.go
  client/client_grpc_dm.go
  client/client_grpc_dm_test.go
  client/errors.go
Labels: approved, ci-passed, enhancement, lgtm, size/L

#136 Add index construct generation
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_bool.go
  entity/columns_bool_test.go
  entity/columns_double.go
  entity/columns_double_test.go
  entity/columns_float.go
  entity/columns_float_test.go
  entity/columns_floatvector.go
  entity/columns_floatvector_test.go
  entity/columns_int16.go
  entity/columns_int16_test.go
  entity/columns_int32.go
  entity/columns_int32_test.go
  entity/columns_int64.go
  entity/columns_int64_test.go
  entity/columns_int8.go
  entity/columns_int8_test.go
  entity/columns_string.go
  entity/columns_string_test.go
  entity/gen/gen.go
  entity/genidx/genidx.go
  entity/index.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
Labels: approved, ci-passed, enhancement, lgtm, size/XXL

#137 Add index search param
  client/client.go
  client/client_grpc_dm.go
  client/client_grpc_dm_test.go
  entity/genidx/genidx.go
  entity/index.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
Labels: approved, ci-passed, enhancement, lgtm, size/XXL

#139 Add index usage example
  client/client.go
  client/client_grpc_dd.go
  client/client_grpc_dd_test.go
  client/client_grpc_tmp.go
  entity/genidx/genidx.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
  examples/README.md
  examples/index/index.go
Labels: approved, ci-passed, documentation, enhancement, lgtm, size/XL

#140 Add CreateIndex sync test case
  client/client_grpc_dd_test.go
Labels: approved, ci-passed, enhancement, lgtm, size/M, test/ut

#142 Change module path to v2
  client/client.go
  client/client_grpc_dd.go
  client/client_grpc_dd_test.go
  client/client_grpc_dm.go
  client/client_grpc_dm_test.go
  client/client_mock_test.go
  entity/columns.go
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_bool.go
  entity/columns_bool_test.go
  entity/columns_double.go
  entity/columns_double_test.go
  entity/columns_float.go
  entity/columns_float_test.go
  entity/columns_floatvector.go
  entity/columns_floatvector_test.go
  entity/columns_int16.go
  entity/columns_int16_test.go
  entity/columns_int32.go
  entity/columns_int32_test.go
  entity/columns_int64.go
  entity/columns_int64_test.go
  entity/columns_int8.go
  entity/columns_int8_test.go
  entity/columns_string.go
  entity/columns_string_test.go
  entity/columns_test.go
  entity/gen/gen.go
  entity/index.go
  entity/schema.go
  entity/segment.go
  entity/segment_test.go
  examples/basic/basic.go
  examples/index/index.go
  examples/insert/insert.go
  go.mod
  go.sum
  internal/proto/common.proto
  internal/proto/common/common.pb.go
  internal/proto/milvus.proto
  internal/proto/schema.proto
  internal/proto/schema/schema.pb.go
  internal/proto/server/milvus.pb.go
  tests/client_collection_test.go
  tests/client_dm_test.go
  tests/client_index_test.go
  tests/client_partition_test.go
  tests/util.go
Labels: approved, ci-passed, enhancement, lgtm, size/XL

#143 Fix v2 docs
  CHANGELOG.md
  README.md
  client/client_grpc_tmp.go
Labels: approved, ci-passed, documentation, lgtm, size/M

#146 Fix examples and tests error due to API change
  client/client_mock_test.go
  examples/insert/insert.go
  internal/proto/milvus.proto
  internal/proto/server/milvus.pb.go
  tests/client_collection_test.go
  tests/client_dm_test.go
  tests/client_index_test.go
  tests/util.go
Labels: approved, ci-passed, lgtm, size/XL

#147 Add CalcDistance api support
  CHANGELOG.md
  client/client.go
  client/client_grpc_dd_test.go
  client/client_grpc_dm.go
  client/client_grpc_dm_test.go
  client/client_mock_test.go
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_bool.go
  entity/columns_bool_test.go
  entity/columns_double.go
  entity/columns_double_test.go
  entity/columns_float.go
  entity/columns_float_test.go
  entity/columns_floatvector.go
  entity/columns_floatvector_test.go
  entity/columns_int16.go
  entity/columns_int16_test.go
  entity/columns_int32.go
  entity/columns_int32_test.go
  entity/columns_int64.go
  entity/columns_int64_test.go
  entity/columns_int8.go
  entity/columns_int8_test.go
  entity/columns_string.go
  entity/columns_string_test.go
  entity/gen/gen.go
  entity/genidx/genidx.go
Labels: approved, ci-passed, enhancement, lgtm, size/L

#148 Add ut test case
  client/client_grpc_dd_test.go
Labels: approved, ci-passed, lgtm, size/S, test/ut

#150 Refactor grpc client function organization
  README.md
  client/client.go
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_index.go
  client/client_grpc_index_test.go
  client/client_grpc_partition.go
  client/client_grpc_partition_test.go
  client/errors.go
Labels: approved, ci-passed, documentation, enhancement, lgtm, size/XXL

#151 Add param constraint
  client/client_grpc_collection_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_index.go
  client/client_grpc_index_test.go
  client/client_grpc_partition.go
  client/client_grpc_partition_test.go
  client/errors.go
  entity/columns.go
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_bool.go
  entity/columns_bool_test.go
  entity/columns_double.go
  entity/columns_double_test.go
  entity/columns_float.go
  entity/columns_float_test.go
  entity/columns_floatvector.go
  entity/columns_floatvector_test.go
  entity/columns_int16.go
  entity/columns_int16_test.go
  entity/columns_int32.go
  entity/columns_int32_test.go
  entity/columns_int64.go
  entity/columns_int64_test.go
  entity/columns_int8.go
  entity/columns_int8_test.go
  entity/columns_string.go
  entity/columns_string_test.go
  entity/gen/gen.go
  entity/genidx/genidx.go
  entity/index.go
  entity/index_test.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
  entity/schema.go
  entity/segment.go
Labels: approved, ci-passed, enhancement, lgtm, size/L

#152 Add param check for Search api
  client/client_grpc_data.go
  client/client_grpc_data_test.go
Labels: approved, ci-passed, enhancement, lgtm, size/L

#154 Implement CalcDistance with vector param feature
  client/client.go
  client/client_grpc_collection_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_partition.go
  client/client_mock_test.go
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_floatvector.go
  entity/columns_floatvector_test.go
  entity/gen/gen.go
Labels: approved, bug, ci-passed, lgtm, size/L

#155 Add CalcDistance example
  examples/README.md
  examples/calcdistance/calc_distance.go
Labels: approved, ci-passed, documentation, lgtm, size/L

#156 Fix readme content
  README.md
Labels: approved, ci-passed, documentation, lgtm, size/S

#158 Fix search with index error
  client/client_grpc_data.go
  entity/genidx/genidx.go
  entity/index.go
  entity/indexes_gen.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
  entity/schema.go
  tests/util.go
Labels: approved, ci-passed, lgtm, size/L

#160 Merge columns files
  entity/columns_binaryvector.go
  entity/columns_binaryvector_test.go
  entity/columns_bool.go
  entity/columns_bool_test.go
  entity/columns_double.go
  entity/columns_double_test.go
  entity/columns_float.go
  entity/columns_float_test.go
  entity/columns_int16.go
  entity/columns_int16_test.go
  entity/columns_int32.go
  entity/columns_int32_test.go
  entity/columns_int64.go
  entity/columns_int64_test.go
  entity/columns_int8.go
  entity/columns_int8_test.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_string.go
  entity/columns_string_test.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
Labels: approved, ci-passed, enhancement, lgtm, size/XXL

#162 Add rows parse
  entity/rows.go
  entity/rows_test.go
Labels: approved, ci-passed, enhancement, lgtm, size/L

#163 Add RowsToColumns util func
  entity/columns.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
  entity/rows.go
  entity/rows_test.go
Labels: approved, ci-passed, lgtm, size/L

#164 Add SearchResult to Rows
  client/client_grpc_row.go
  client/client_grpc_row_test.go
Labels: approved, ci-passed, lgtm, size/L

#165 Update README.md
  README.md
Labels: approved, ci-passed, lgtm, size/XS

#168 Split Search request according to row size
  client/client_grpc_data.go
  client/client_grpc_data_test.go
Labels: approved, ci-passed, enhancement, lgtm, size/L
