Repository milvus-io/milvus-sdk-go, pull requests merged in 2022-09, with the labels that each got.

#313 Fix bug: collection cache missed caused by empty collectionName
  client/client_grpc_collection.go
Labels: lgtm, approved, ci-passed, size/XS

#311 flush segment before create index
  client/client_grpc_index.go
  client/client_grpc_index_test.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#309 Expose GetPersistentSegmentInfo Interface
  client/client.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XS
