Repository milvus-io/milvus-sdk-go, pull requests merged in 2022-01, with the labels that each got.

#233 Fix spell error and check empty array
  client/client.go
  client/client_grpc_data.go
  client/client_grpc_partition.go
  client/client_grpc_partition_test.go
  entity/collection.go
  examples/basic/basic.go
  tests/testutil/utils.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#235 Use GetFlushState to check Flush progress
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_mock_test.go
  internal/proto/common.proto
  internal/proto/common/common.pb.go
  internal/proto/milvus.proto
  internal/proto/server/milvus.pb.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XXL

#238 Return error when CreateCollection response has error
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#240 Add Alias related API
  client/client.go
  client/client_grpc_alias.go
  client/client_grpc_alias_test.go
  client/client_mock_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#242 Add compaction API
  client/client.go
  client/client_grpc_control.go
  client/client_grpc_control_test.go
  client/client_mock_test.go
  client/client_test.go
  entity/compaction.go
  internal/utils/tso/tso.go
  internal/utils/tso/tso_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL

#244 Add Delete API
  client/client.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_mock_test.go
  client/client_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#246 Set loaded flag in ListCollections
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#248 Implement Query By primary keys API
  client/client.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_mock_test.go
  entity/columns.go
  entity/columns_scalar_gen_test.go
  entity/gen/gen.go
Labels: lgtm, approved, ci-passed, size/L, kind/feature

#249 Fix search scores index searching multiple vectors
  client/client_grpc_data.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#251 Make ListCollections and ShowParitions work with unloaded ones
  client/client_grpc_collection.go
  client/client_grpc_partition.go
  client/client_grpc_partition_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#253 Use const value for vector field dimension key
  client/client_grpc_collection_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_mock_test.go
  entity/rows.go
  entity/schema.go
  examples/basic/basic.go
  examples/calcdistance/calc_distance.go
  examples/index/index.go
  examples/insert/insert.go
  tests/client_collection_test.go
  tests/testutil/utils.go
  tests/util.go
Labels: lgtm, approved, ci-passed, size/M

#254 Add unit tests for index related apis
  client/client_grpc_index_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#256 Handle vector field data in QueryByPks
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  entity/columns.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
Labels: kind/bug, kind/enhancement, lgtm, approved, ci-passed, size/L

#257 Fix README.md for v2.0.0 and remove banner
  README.md
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement
