Repository milvus-io/milvus-sdk-go, pull requests merged in 2022-07, with the labels that each got.

#285 Support login with username and password
  client/client.go
  client/client_grpc_authentication.go
  client/client_grpc_authentication_test.go
  client/client_grpc_collection.go
  client/client_grpc_options.go
  client/client_mock_test.go
  client/interceptor.go
  client/interceptor_test.go
  examples/auth/auth.go
  internal/utils/crypto/crypto.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL

#288 Fix timestamp bug
  client/client_grpc_data.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#289 Add example for searching with specified consistency level
  examples/query/query.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#293 Fix lint issue reported by golangci-lint
  .golangci.yml
  client/client_grpc_authentication.go
  client/client_grpc_authentication_test.go
  client/client_grpc_collection_test.go
  client/client_grpc_control.go
  client/client_grpc_control_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_options.go
  client/client_grpc_options_test.go
  client/client_grpc_partition_test.go
  client/client_grpc_row.go
  client/client_mock_test.go
  client/interceptor.go
  client/interceptor_test.go
  client/timestamp_map_test.go
  entity/columns_varchar.go
  entity/columns_varchar_test.go
  entity/compaction.go
  entity/rows.go
  entity/schema.go
  entity/schema_test.go
  entity/until_fail.sh
  examples/auth/auth.go
  examples/basic/basic.go
  examples/calcdistance/calc_distance.go
  examples/hello_milvus/hello_milvus.go
  examples/index/index.go
  examples/insert/insert.go
  examples/query/query.go
  examples/tls/tls.go
  examples/varchar/varchar_pk.go
  tests/client_collection_test.go
  tests/collection_test.go
  tests/connect_test.go
  tests/main_test.go
  tests/testutil/common.go
  tests/testutil/utils.go
  tests/util.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#294 Add golangci-lint workflow for PR and mergify rules
  .github/mergify.yml
  .github/workflows/golangci-lint.yml
  client/client_grpc_partition.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#295 Fix PlaceHolderValue type is wrong when searching binary vector
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  entity/columns.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#298 Update README.md for v2.1.0
  README.md
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#296 Fix e2e test
  tests/client_collection_test.go
  tests/client_dm_test.go
  tests/client_index_test.go
  tests/collection_test.go
  tests/main_test.go
  tests/util.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement
