Repository milvus-io/milvus-sdk-go, pull requests merged in 2022-04, with the labels that each got.

#264 Add ConsistencyLevel support in CreateCollection
  client/client.go
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
  client/client_grpc_options.go
  client/client_grpc_options_test.go
  client/client_test.go
  entity/schema.go
  entity/schema_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/feature

#262 Remove duplicate checks
  client/client_grpc_collection.go
  client/client_grpc_control.go
  client/client_grpc_data.go
  client/client_grpc_partition.go
  client/client_grpc_row.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#269 1.x supoort modify grpc client option
  milvus/ClientProxy.go
  milvus/MilvusClient.go
Labels: kind/enhancement, lgtm
