Repository milvus-io/milvus-sdk-go, pull requests merged in 2022-11, with the labels that each got.

#327 Use proto in milvus-proto instead of local
  client/client_grpc_alias.go
  client/client_grpc_alias_test.go
  client/client_grpc_authentication.go
  client/client_grpc_authentication_test.go
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
  client/client_grpc_control.go
  client/client_grpc_control_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_index.go
  client/client_grpc_index_test.go
  client/client_grpc_options.go
  client/client_grpc_options_test.go
  client/client_grpc_partition.go
  client/client_grpc_partition_test.go
  client/client_grpc_row.go
  client/client_grpc_row_test.go
  client/client_mock_test.go
  client/client_test.go
  client/rate_limit_interceptor.go
  client/rate_limit_interceptor_test.go
  entity/columns.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_test.go
  entity/columns_varchar.go
  entity/columns_varchar_test.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/index.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
  entity/schema.go
  entity/schema_test.go
  entity/segment.go
  entity/segment_test.go
  go.mod
  go.sum
  internal/proto/common/common.pb.go
  internal/proto/schema/schema.pb.go
  internal/proto/server/milvus.pb.go
Labels: lgtm, approved, ci-passed, size/XXL

#333 Remove unused index file
  client/client_grpc_index_v2.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#332 Add a NewDefaultGrpcClientWithURI API
  client/client.go
  client/client_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#336 Add new test cases and milvus client struct and response check and ut…
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/connect_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/main_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement, test/ci

#338 Add ci test workflow and operator log exporter and default milvus yaml
  .github/workflows/test-ci.yaml
  ci/milvus-operator/milvus-cluster.yaml
  ci/milvus-operator/milvus-standalone.yaml
  ci/scripts/export_log_k8s_for_operator.sh
  test/testcases/insert_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement, test/ci

#340 Merge index name option to simplify client
  client/client.go
  client/client_grpc_index.go
  client/client_grpc_index_test.go
  client/v2/client.go
  client/v2/client_grpc_index.go
  client/v2/client_grpc_index_test.go
  examples/index/index_v2/index_v2.go
  scripts/run_go_unittest.sh
  test/base/milvus_client.go
Labels: lgtm, approved, ci-passed, size/XXL, kind/improvement, test/ci

#341 Add ci test in mergify
  .github/mergify.yml
  .github/workflows/test-ci.yaml
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#344 Add collection cases and update check err func
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/connect_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/main_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement, test/ci

#347 Fix CreateIndex check building progress behavior
  client/client_grpc_index.go
  client/client_grpc_index_test.go
  examples/hello_milvus/hello_milvus.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#348 Fix mergify rule for e2e
  .github/mergify.yml
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#350 Add query and pagination
  client/client.go
  client/client_grpc_collection_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_options.go
  client/client_grpc_options_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#349 Add connect and insert cases
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/connect_test.go
  test/testcases/insert_test.go
  test/testcases/main_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement

#353 Add RBAC APIs
  client/client.go
  client/client_grpc_rbac.go
  client/client_grpc_rbac_test.go
  client/client_test.go
  entity/rbac.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
  scripts/run_go_unittest.sh
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#356 Fix mergify rules for e2e case only
  .github/mergify.yml
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#363 Add index cases
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/connect_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/main_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement, test/ci
