Repository milvus-io/milvus-sdk-go, pull requests merged in 2022-10, with the labels that each got.

#315 fix readme to current example
  README.md
Labels: lgtm, approved, ci-passed, size/XS

#320 Retry on rate limit
  client/client.go
  client/rate_limit_interceptor.go
  client/rate_limit_interceptor_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#322 Rename bulkload to bulkinsert and support options
  client/client.go
  client/client_grpc_data.go
  client/client_grpc_options.go
  entity/bulkinsert.go
  entity/bulkload.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#324 Set nq param in SearchRequest
  client/client_grpc_data.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#329 Add nightly ci framework
  .github/workflows/nightly_ci.yml
  ci/docker/milvus/docker-compose.yml
  ci/scripts/docker_image_find_tag.sh
  tests/e2e/connect_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L
