Repository milvus-io/milvus-sdk-go, pull requests merged in 2022-08, with the labels that each got.

#301 Remove redundant checks and add MetaCache
  client/client.go
  client/client_grpc_collection.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_options.go
  client/client_grpc_options_test.go
  client/client_grpc_row.go
  client/meta_cache.go
  client/meta_cache_test.go
  client/timestamp_map.go
  client/timestamp_map_test.go
  examples/query/query.go
Labels: lgtm, approved, ci-passed, size/XL

#302 Fix delete with varchar primary key
  client/client_grpc_data.go
  examples/hello_milvus/hello_milvus.go
  examples/varchar/varchar_pk.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#303 Add retry mechanism for retryable error codes
  client/client_grpc_collection.go
  client/client_test.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#304 To compatiable with auth interceptor for Grpc opts
  client/client.go
  client/client_grpc_collection.go
  client/client_test.go
  examples/auth/auth.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#306 add client tracing interfaces
  client/ctx.go
  client/ctx_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M
