Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-10, with the labels that each got.

#595 Fix `TestUsingDb` case error message
  test/testcases/database_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#592 Add count and query test cases
  test/base/milvus_client.go
  test/common/utils.go
  test/testcases/delete_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, test/ci

#597 Fix SCANN index type used ivf_flat value
  entity/genidx/genidx.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#598 Remove `Flush` operation before create index
  client/index.go
  client/index_test.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#599 Add case for scann index and range search
  test/common/utils.go
  test/testcases/index_test.go
  test/testcases/main_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL, test/ci

#601 Fix typos
  client/client.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#605 Fix L0 testcase TestDropDb error msg
  test/testcases/database_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#604 Add wildcard outputfield expansion logic back
  client/data.go
  client/data_test.go
  test/testcases/search_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#525 impl check health
  client/admin.go
  client/admin_test.go
  client/client.go
  entity/check_health.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#607 Support Array datatype
  entity/columns.go
  entity/columns_array_gen.go
  entity/columns_varchar_test.go
  entity/genarray/gen_array.go
  entity/schema.go
  entity/schema_test.go
  examples/array/hello_array.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#606 Bump SDK Version & milvus-proto/go-api to v2.3.2
  client/client_mock_test.go
  common/common.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement
