Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-06, with the labels that each got.

#477 [2.2.x] Update query example code
  examples/query/query.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#479 [2.2.x] Change collection default consistency level
  client/collection.go
  client/collection_test.go
  test/common/utils.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement

#464 Update to support milvus-backup
  client/client.go
  client/insert.go
  client/options.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M

#483 Remove HasCollection check for create collection
  client/collection.go
  client/collection_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#485 Use milvus-proto/go-api/v2
  client/admin.go
  client/alias.go
  client/alias_test.go
  client/authentication.go
  client/authentication_test.go
  client/client_mock_test.go
  client/client_test.go
  client/collection.go
  client/collection_test.go
  client/data.go
  client/data_test.go
  client/database.go
  client/database_test.go
  client/index.go
  client/index_test.go
  client/insert.go
  client/insert_test.go
  client/maintainance.go
  client/maintainance_test.go
  client/options.go
  client/options_test.go
  client/partition.go
  client/partition_test.go
  client/rate_limit_interceptor.go
  client/rate_limit_interceptor_test.go
  client/rbac.go
  client/rbac_test.go
  client/resource_group.go
  client/resource_group_test.go
  client/row.go
  client/row_test.go
  entity/columns.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_test.go
  entity/columns_varchar.go
  entity/columns_varchar_test.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
  entity/index.go
  entity/rbac.go
  entity/schema.go
  entity/schema_test.go
  entity/segment.go
  entity/segment_test.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#486 Fix api token format
  client/interceptor.go
  client/interceptor_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#489 Use milvus-proto/go-api/v2 for master
  Makefile
  client/admin.go
  client/alias.go
  client/alias_test.go
  client/authentication.go
  client/authentication_test.go
  client/client_mock_test.go
  client/client_test.go
  client/collection.go
  client/collection_test.go
  client/connect.go
  client/data.go
  client/data_test.go
  client/index.go
  client/index_test.go
  client/insert.go
  client/insert_test.go
  client/maintainance.go
  client/maintainance_test.go
  client/options.go
  client/options_test.go
  client/partition.go
  client/partition_test.go
  client/rate_limit_interceptor.go
  client/rate_limit_interceptor_test.go
  client/rbac.go
  client/rbac_test.go
  client/resource_group.go
  client/resource_group_test.go
  client/row.go
  client/row_test.go
  entity/columns.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_test.go
  entity/columns_varchar.go
  entity/columns_varchar_test.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
  entity/index.go
  entity/rbac.go
  entity/schema.go
  entity/schema_test.go
  entity/segment.go
  entity/segment_test.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement

#491 [Enhancement] use grpc.DialContext in client.NewClient
  client/collection.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#494 Bump milvus-proto v2.2.10 SDK version v2.2.4
  client/grpc_client.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#495 Add database cases and fix delete cases
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/connect_test.go
  test/testcases/database_test.go
  test/testcases/delete_test.go
  test/testcases/main_test.go
Labels: lgtm, approved, ci-passed, size/L, test/ci

#496 Add NewCollection high level API
  client/client.go
  client/collection.go
  client/collection_test.go
  client/options.go
  client/options_test.go
  entity/collection.go
  entity/index.go
  test/testcases/database_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#498 Support scalar index
  client/data.go
  client/grpc_client.go
  client/index.go
  entity/index.go
  entity/index_scalar.go
  examples/index/index.go
  test/testcases/index_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#502 Add highlevel API `Get`
  client/client.go
  client/data.go
  client/data_test.go
  client/options.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#501 [Feature|Pick] Support Database for managing collection and index
  README.md
  client/client.go
  client/client_mock_test.go
  client/client_test.go
  client/config.go
  client/config_test.go
  client/connect.go
  client/database.go
  client/database_test.go
  client/interceptor.go
  client/interceptor_test.go
  docs/new_client.md
  entity/database.go
  examples/README.md
  examples/auth/auth.go
  examples/basic/basic.go
  examples/calcdistance/calc_distance.go
  examples/database/database.go
  examples/hello_milvus/hello_milvus.go
  examples/index/index.go
  examples/insert/insert.go
  examples/query/query.go
  examples/tls/tls.go
  examples/varchar/varchar_pk.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
  test/base/milvus_client.go
  test/testcases/database_test.go
  test/testcases/main_test.go
Labels: lgtm, approved, ci-passed, size/XXL, kind/feature

#505 Add PK max length option
  client/collection.go
  client/options.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#506 Enable dynamic schema for high-level newcollection by default
  client/collection.go
  client/options.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement
