Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-03, with the labels that each got.

#412 Add mock server suite base
  client/client_grpc_alias_test.go
  client/client_grpc_authentication_test.go
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
  client/client_grpc_control_test.go
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_index_test.go
  client/client_grpc_options.go
  client/client_grpc_partition.go
  client/client_grpc_partition_test.go
  client/client_grpc_rbac_test.go
  client/client_grpc_row.go
  client/client_grpc_row_test.go
  client/client_mock_test.go
  client/client_test.go
  client/errors.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement

#406 add IgnoreGrowing option
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_options.go
  client/client_grpc_options_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M

#414 Refactor collection list,create unit test
  client/client_grpc_collection_test.go
  client/client_mock_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#421 Update mergify.yml
  .github/mergify.yml
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#418 Remove test teardown clear all collections
  test/testcases/main_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#419 Remove test teardown clear all collections
  test/testcases/main_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#397 Support get bulk insert progress
  entity/bulkinsert.go
Labels: lgtm, approved, size/S, ci-passed

#425 Add RenameCollection API
  client/client.go
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M

#420 Set default consistency level to Bounded
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
  test/common/utils.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#431 add IgnoreGrowing option (#406)
  client/client_grpc_data.go
  client/client_grpc_data_test.go
  client/client_grpc_options.go
  client/client_grpc_options_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M
