Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-11, with the labels that each got.

#615 Fix unsafe direct field access for Int8/Int16 result data
  client/data_test.go
  entity/columns.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#617 Remove field check logic for upsert
  client/insert.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#614 Add upsert test cases
  test/common/utils.go
  test/testcases/insert_test.go
  test/testcases/main_test.go
  test/testcases/option.go
  test/testcases/query_test.go
  test/testcases/upsert_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement, test/ci

#620 Fix `TestUpsertInvalidColumnData` case using dynamic schema
  test/testcases/upsert_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS, test/ci

#619 Fix QueryByPKs composes wrong expr when pk data has spaces
  client/data.go
  test/testcases/upsert_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#621 Support row based Array & fix varchar array type
  entity/columns.go
  entity/columns_array.go
  entity/columns_array_gen.go
  entity/columns_varchar_test.go
  entity/genarray/gen_array.go
  entity/rows.go
  entity/schema.go
Labels: kind/bug, lgtm, approved, ci-passed, size/L

#624 Parse result field data when result set entry count is not zero
  client/data.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#616 Add array field type test cases
  test/common/response_check.go
  test/common/utils.go
  test/common/utils_client.go
  test/testcases/collection_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/main_test.go
  test/testcases/option.go
  test/testcases/partition_key_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
  test/testcases/upsert_test.go
Labels: lgtm, approved, ci-passed, size/XXL, test/ci

#622 Support the replicate message api
  client/client.go
  client/client_mock_test.go
  client/collection.go
  client/collection_test.go
  client/data_test.go
  client/database.go
  client/database_test.go
  client/index.go
  client/index_test.go
  client/insert.go
  client/mq_message.go
  client/mq_message_test.go
  client/options.go
  client/options_msg_base.go
  client/partition.go
  client/partition_test.go
  entity/mq_message.go
  go.sum
  mocks/MilvusServiceServer.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL, kind/improvement

#625 Bump version & make Collection Option EnableDynamicSchema work
  client/collection.go
  common/common.go
  go.mod
  go.sum
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/L, kind/improvement

#626 Fix the typo error for the WithReleasePartitionMsgBase option
  client/options_msg_base.go
  client/partition_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#630 Update cases due to error message change
  test/testcases/database_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/resource_group_test.go
  test/testcases/upsert_test.go
Labels: lgtm, approved, size/S, ci-passed, test/ci

#631 Fix case failed in nightly
  test/testcases/collection_test.go
  test/testcases/index_test.go
Labels: lgtm, approved, ci-passed, size/XS, test/ci
