Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-04, with the labels that each got.

#434 [2.2.x] Add AlterCollection API
  client/client.go
  client/client_grpc_collection.go
  client/client_grpc_collection_test.go
  client/client_mock_test.go
  entity/collection_attr.go
  entity/collection_attr_test.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement

#436 Remove ANNOY index type
  .github/workflows/test-ci.yaml
  .gitignore
  docs/index_limitations.md
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
  entity/genidx/genidx.go
  entity/index.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
  test/common/utils.go
  test/testcases/index_test.go
  test/testcases/search_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XL

#435 Add AlterCollection API
  client/client.go
  client/client_mock_test.go
  client/collection.go
  client/collection_test.go
  entity/collection_attr.go
  entity/collection_attr_test.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement

#441 Use Milvus default shard number
  docs/create_collection.md
  entity/collection.go
  examples/basic/basic.go
  examples/calcdistance/calc_distance.go
  examples/hello_milvus/hello_milvus.go
  examples/index/index.go
  examples/insert/insert.go
  examples/query/query.go
  examples/tls/tls.go
  examples/varchar/varchar_pk.go
  test/testcases/search_test.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#440 [2.2.x] Use Milvus default shard number
  docs/create_collection.md
  entity/collection.go
  examples/basic/basic.go
  examples/calcdistance/calc_distance.go
  examples/hello_milvus/hello_milvus.go
  examples/index/index.go
  examples/insert/insert.go
  examples/query/query.go
  examples/tls/tls.go
  examples/varchar/varchar_pk.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#443 Add JSON data type
  entity/columns_json.go
  entity/columns_json_test.go
  entity/schema.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#444 Support to search/query json
  entity/columns.go
Labels: lgtm, approved, size/S, ci-passed, kind/feature

#447 Fix vector field type check logic
  entity/columns.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed
