Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-08, with the labels that each got.

#529 modify the description
  examples/insert/insert.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#513 Add json field and dynamic field test cases
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/common/utils_client.go
  test/testcases/collection_test.go
  test/testcases/configure_test.go
  test/testcases/connect_test.go
  test/testcases/database_test.go
  test/testcases/delete_test.go
  test/testcases/flush_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/load_release_test.go
  test/testcases/main_test.go
  test/testcases/query_test.go
  test/testcases/resource_group_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XXL, test/ci

#532 Sync InsertRows and config related PR to master
  client/client.go
  client/config.go
  client/config_test.go
  client/rate_limit_interceptor.go
  client/rate_limit_interceptor_test.go
  client/row.go
  entity/rows.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#534 fix: log info error
  examples/tls/tls.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#535 Add pass rule for example code change
  .github/mergify.yml
Labels: lgtm, approved, size/S, ci-passed, kind/improvement, kind/workflow

#536 Remove set default partition name logic
  client/insert.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#540 Fix mergify example code rule file path
  .github/mergify.yml
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, kind/workflow

#539 Add partition key example
  examples/partitionkey/main.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#533 [cherry-pick]Add cases about resource group and database
  client/options.go
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/connect_test.go
  test/testcases/database_test.go
  test/testcases/delete_test.go
  test/testcases/main_test.go
  test/testcases/resource_group_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement, test/ci

#542 Fix nightly config not found
  .github/workflows/nightly_ci.yml
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, kind/workflow

#543 Fix resource group L3 case code
  test/testcases/resource_group_test.go
Labels: lgtm, approved, ci-passed, kind/improvement, test/ci

#541 Cherry pick partition key fix and example
  client/insert.go
  examples/partitionkey/main.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#545 Configure schedule nightly for branch v2.2.x
  .github/workflows/nightly_ci.yml
  ci/milvus-operator/milvus-nightly.yaml
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#548 Add milvus-nightly.yaml for v2.2.x branch
  ci/milvus-operator/milvus-nightly.yaml
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#544 Add partition key cases
  test/common/utils.go
  test/testcases/partition_key_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement, test/ci

#549 Remove time travel
  client/data.go
  client/maintainance.go
  client/maintainance_test.go
  client/options.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#550 Support GPU index type and search param
  entity/genidx/genidx.go
  entity/index.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#546 Add highlevel cases and update utils func
  .github/workflows/test-ci.yaml
  test/base/milvus_client.go
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/delete_test.go
  test/testcases/highlevel_test.go
  test/testcases/index_test.go
  test/testcases/load_release_test.go
  test/testcases/main_test.go
  test/testcases/partition_key_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement, PR | need Cherry-Pick

#551 Change nightly job name for branches
  .github/workflows/nightly_ci.yml
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, kind/workflow

#552 Support SCANN index type
  entity/genidx/genidx.go
  entity/index.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#553 [Cherry-Pick] Support scalar index (#498)
  client/data.go
  client/index.go
  entity/index.go
  entity/index_scalar.go
  examples/index/index.go
  test/testcases/index_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#547 Update L3 cases and nightly qn replicas
  ci/milvus-operator/milvus-nightly.yaml
  test/testcases/resource_group_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#554 Remove the field name check of the drop index api
  client/index.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#557 Support append struct/map to json column
  entity/columns_json.go
  entity/columns_json_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#558 Update L3 cases and nightly qn replicas (#547)
  ci/milvus-operator/milvus-nightly.yaml
  test/testcases/resource_group_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#556 Add json dynamic filed, partition key, highlevel test cases
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/common/utils_client.go
  test/testcases/collection_test.go
  test/testcases/connect_test.go
  test/testcases/database_test.go
  test/testcases/delete_test.go
  test/testcases/flush_test.go
  test/testcases/highlevel_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/load_release_test.go
  test/testcases/main_test.go
  test/testcases/partition_key_test.go
  test/testcases/query_test.go
  test/testcases/resource_group_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XXL, kind/improvement, test/ci

#559 Remove empty index type param
  entity/index.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#560 Add back testcases skipped for issue 555
  test/testcases/highlevel_test.go
  test/testcases/index_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#437 Bump golang.org/x/net version manually
  .github/workflows/golangci-lint.yml
  client/client_mock_test.go
  client/client_test.go
  client/data.go
  client/maintainance.go
  client/options.go
  client/row.go
  entity/resource_group.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#561 Bump proto version to 2.3.0
  Makefile
  client/client_mock_test.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#562 Refine code style, examples & documents
  README.md
  client/admin.go
  client/alias.go
  client/alias_test.go
  client/authentication.go
  client/authentication_test.go
  client/client.go
  client/client_mock_test.go
  client/client_test.go
  client/collection.go
  client/collection_test.go
  client/data.go
  client/data_test.go
  client/database.go
  client/database_test.go
  client/grpc_client.go
  client/index.go
  client/index_test.go
  client/insert.go
  client/insert_test.go
  client/maintainance.go
  client/maintainance_test.go
  client/options.go
  client/options_test.go
  client/partition.go
  client/partition_test.go
  client/rate_limit_interceptor.go
  client/rate_limit_interceptor_test.go
  client/rbac.go
  client/rbac_test.go
  client/resource_group.go
  client/resource_group_test.go
  client/row.go
  client/row_test.go
  common/common.go
  examples/basic/basic.go
  examples/hello_milvus/hello_milvus.go
  examples/insert/insert.go
  examples/query/query.go
  test/testcases/partition_key_test.go
Labels: lgtm, approved, ci-passed, size/XXL, kind/improvement

#564 Manually bump golang/x/net to 0.7.0 for v2.2.x
  .github/workflows/golangci-lint.yml
  client/client_mock_test.go
  client/client_test.go
  client/data.go
  client/row.go
  entity/resource_group.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#565 Bump SDK version to v2.2.8
  client/grpc_client.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#567 Update to support milvus-backup
  client/client.go
  client/insert.go
  client/options.go
Labels: lgtm, approved, ci-passed, size/M
