Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-09, with the labels that each got.

#574 Fix master branch ci cases
  test/testcases/index_test.go
  test/testcases/search_test.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed, test/ci

#569 Remove a outdated comment
  client/index.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#576 Use DescribeCollection for HasCollection impl
  client/client_mock_test.go
  client/collection.go
  client/collection_test.go
  client/insert_test.go
  client/partition_test.go
  client/row_test.go
  entity/schema.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, kind/improvement

#580 Update 2.2.x version
  README.md
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#578 add delete by expression method
  client/client.go
  client/data_test.go
  client/insert.go
  test/base/milvus_client.go
Labels: lgtm, approved, ci-passed, size/L

#581 ScaNN support with_raw_data build option
  entity/genidx/genidx.go
  entity/indexes_gen.go
  entity/indexes_gen_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#583 Fix nightly `TestTransferReplicaNotExistedCollection` case err msg
  test/testcases/resource_group_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#586 Fix nightly case `TestSearchInvalidExpr` error msg
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#585 Fix outputFields logic conflicted between aggr & dynamic schema
  client/data.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#587 Remove default partition name logic from `InsertRows` and `Upsert`
  client/insert.go
  client/row.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#588 Bump version to v2.3.1
  .github/workflows/main.yml
  .github/workflows/test-ci.yaml
  README.md
  common/common.go
  go.mod
  go.sum
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#590 Fix e2e case error message due to milvus change
  test/testcases/index_test.go
  test/testcases/load_release_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#589 Use mockery for Alias series API unittest
  client/alias_test.go
  client/client_mock_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement
