Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-07, with the labels that each got.

#504 Add forTuning option
  client/data.go
  client/data_test.go
  client/options.go
  client/options_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#508 Add back CollectionProperty option
  client/collection.go
  client/options.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#510 Fix nightly ci action
  .github/workflows/nightly_ci.yml
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#511 Fix workflow syntax & mergify condition
  .github/mergify.yml
  .github/workflows/nightly_ci.yml
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#514 Support default value
  client/insert.go
  client/insert_test.go
  entity/columns.go
  entity/schema.go
  entity/schema_test.go
Labels: lgtm, approved, ci-passed, size/L

#516 Sync v2.2.x change to master
  client/client.go
  client/collection.go
  client/collection_test.go
  client/config.go
  client/data.go
  client/data_test.go
  client/database.go
  client/errors.go
  client/grpc_client.go
  client/interceptor.go
  client/interceptor_test.go
  client/options.go
  client/options_test.go
  client/partition.go
  client/partition_test.go
  client/results.go
  entity/collection.go
Labels: lgtm, approved, ci-passed, size/XXL, kind/improvement

#517 Increase the number of retry times
  client/config.go
  client/rate_limit_interceptor.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#520 Increase the number of retry times (#517)
  client/config.go
  client/rate_limit_interceptor.go
Labels: lgtm, approved, ci-passed, size/XS

#522 Make retry on ratelimit configurable
  client/client.go
  client/config.go
  client/rate_limit_interceptor.go
  client/rate_limit_interceptor_test.go
  client/results.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#521 Make SearchParams extensible
  entity/genidx/genidx.go
  entity/index.go
  entity/indexes_search_param_gen.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#527 Auto fill 443 port for https schema url
  client/config.go
  client/config_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#519 Support range search
  entity/index.go
  entity/index_test.go
Labels: lgtm, approved, size/S, ci-passed

#528 Add yah01 as OWNER
  OWNERS
Labels: approved, ci-passed, size/XS, kind/improvement
