Repository milvus-io/milvus-sdk-go, pull requests merged in 2023-05, with the labels that each got.

#450 Handle LongData returned when queryresult is empty
  entity/columns.go
  entity/columns_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#451 [Cherry-Pick] Handle LongData returned when queryresult is empty (#450)
  entity/columns.go
  entity/columns_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#452 Add AutoCompactionEnabled collection attribute
  entity/collection_attr.go
  entity/collection_attr_test.go
  test/testcases/index_test.go
  test/testcases/load_release_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#453 Update doc link
  README.md
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#454 Add COSINE metric type
  entity/index.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#455 Adapt dynamic field and support insert column when dynamic field enabled
  client/client_grpc_partition_test.go
  client/client_mock_test.go
  client/data.go
  client/data_test.go
  client/insert.go
  client/insert_test.go
  client/row.go
  codecov.yml
  entity/columns.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_varchar.go
  entity/columns_vector_gen.go
  entity/gen/gen.go
  entity/schema.go
  entity/schema_test.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
  test/testcases/insert_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#456 Adapt dynamic field and support insert by rows
  client/client_mock_test.go
  client/meta_cache.go
  client/row.go
  client/row_test.go
  entity/rows.go
  entity/rows_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#457 Support search & query with dynamic schema
  client/client.go
  client/client_mock_test.go
  client/data.go
  client/data_test.go
  client/row_test.go
  entity/columns.go
  entity/columns_dynamic.go
  entity/columns_dynamic_test.go
  entity/schema.go
  entity/schema_test.go
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#458 Improve file naming and schema creation usage
  client/admin.go
  client/alias.go
  client/alias_test.go
  client/authentication.go
  client/authentication_test.go
  client/client_test.go
  client/collection.go
  client/collection_test.go
  client/connect.go
  client/data_test.go
  client/index.go
  client/index_test.go
  client/maintainance.go
  client/maintainance_test.go
  client/options.go
  client/options_test.go
  client/partition.go
  client/partition_test.go
  client/rbac.go
  client/rbac_test.go
  client/resource_group.go
  client/resource_group_test.go
  entity/schema.go
  entity/schema_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#460 Add PartitionKey definition for schema
  entity/schema.go
  entity/schema_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#449 Support Database for managing collection and index
  README.md
  client/client.go
  client/client_grpc_collection.go
  client/client_grpc_database.go
  client/client_grpc_database_test.go
  client/client_grpc_rbac_test.go
  client/client_mock_test.go
  client/client_test.go
  client/config.go
  client/config_test.go
  client/interceptor.go
  client/interceptor_test.go
  docs/new_client.md
  entity/database.go
  examples/README.md
  examples/auth/auth.go
  examples/basic/basic.go
  examples/calcdistance/calc_distance.go
  examples/database/database.go
  examples/hello_milvus/hello_milvus.go
  examples/index/index.go
  examples/insert/insert.go
  examples/query/query.go
  examples/tls/tls.go
  examples/varchar/varchar_pk.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
  test/base/milvus_client.go
  test/testcases/database_test.go
  test/testcases/index_test.go
  test/testcases/main_test.go
Labels: lgtm, approved, ci-passed, size/XXL

#461 Support JSON datatype
  client/admin.go
  client/alias.go
  client/alias_test.go
  client/authentication.go
  client/authentication_test.go
  client/client_mock_test.go
  client/collection.go
  client/collection_test.go
  client/data.go
  client/data_test.go
  client/database.go
  client/database_test.go
  client/index.go
  client/index_test.go
  client/maintainance.go
  client/maintainance_test.go
  client/options.go
  client/options_test.go
  client/partition.go
  client/partition_test.go
  client/rbac.go
  client/rbac_test.go
  client/resource_group.go
  client/resource_group_test.go
  client/row.go
  client/row_test.go
  entity/columns_json.go
  entity/columns_json_test.go
  entity/schema.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#462 Support anonymous dynamic schema
  client/client_mock_test.go
  client/data.go
  client/data_test.go
  client/insert.go
  client/insert_test.go
  client/row_test.go
  entity/columns.go
  entity/columns_json.go
  entity/columns_json_test.go
  entity/rows.go
  entity/rows_test.go
  entity/schema.go
  entity/schema_test.go
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#463 Support dynamic schema for 2.2.x
  client/client.go
  client/client_mock_test.go
  client/data.go
  client/data_test.go
  client/insert.go
  client/insert_test.go
  client/meta_cache.go
  client/row.go
  client/row_test.go
  codecov.yml
  entity/columns.go
  entity/columns_dynamic.go
  entity/columns_dynamic_test.go
  entity/columns_json.go
  entity/columns_json_test.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_varchar.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
  entity/rows.go
  entity/rows_test.go
  entity/schema.go
  entity/schema_test.go
  go.mod
  go.sum
  test/testcases/insert_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#465 [2.2.x] Support row interface with map[string]any
  entity/rows.go
  entity/rows_test.go
  examples/dynamic_schema/dynamic_schema.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#466 Support row interface with map[string]any
  entity/rows.go
  entity/rows_test.go
  examples/dynamic_schema/dynamic_schema.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#467 Add Logical partition num options for create collection
  client/collection.go
  client/options.go
  client/options_test.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#468 [2.2.x] Add logical partition num option for create collection
  client/collection.go
  client/options.go
  client/options_test.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#469 [2.2.x] Improve ResultSet & Column Get methods
  client/client.go
  client/client_mock_test.go
  client/data_test.go
  client/partition.go
  client/rbac_test.go
  client/resource_group_test.go
  entity/columns.go
  entity/columns_conversion.go
  entity/columns_dynamic.go
  entity/columns_dynamic_test.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_varchar.go
  entity/columns_vector_gen.go
  entity/gen/gen.go
  examples/dynamic_schema/dynamic_schema.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#470 Ignore AutoID pk when converting rows to columns
  entity/rows.go
  entity/rows_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#471 Improve ResultSet & Column Get methods
  client/client.go
  client/client_mock_test.go
  client/data_test.go
  client/partition.go
  client/resource_group_test.go
  entity/columns.go
  entity/columns_conversion.go
  entity/columns_dynamic.go
  entity/columns_dynamic_test.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_varchar.go
  entity/columns_vector_gen.go
  entity/gen/gen.go
  examples/dynamic_schema/dynamic_schema.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#472 Ignore AutoID pk when converting rows to columns (#470)
  entity/rows.go
  entity/rows_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#473 [2.2.x] Support API token config
  client/config.go
  client/config_test.go
  client/interceptor.go
  client/interceptor_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#474 Add InsertRows API and mark InsertByRows deprecated
  client/client.go
  client/row.go
  entity/rows.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#475 [2.2.x] Handle wildcard and outputFields
  client/data.go
  entity/schema.go
  examples/dynamic_schema/dynamic_schema.go
Labels: lgtm, approved, ci-passed, size/M
