Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-07, with the labels that each got.

#778 fix: update err msg and max partition num
  .github/workflows/test-ci.yaml
  test/common/response_check.go
  test/common/utils.go
  test/testcases/index_test.go
  test/testcases/load_release_test.go
  test/testcases/partition_key_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
  test/testcases/upsert_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL

#781 test: Add BITMAP index cases
  entity/index.go
  entity/index_scalar_test.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/index_test.go
  test/testcases/query_test.go
Labels: lgtm, approved, ci-passed, size/L

#780 enhance: Remove the logic to set replica_number=1 by default
  client/collection.go
  client/collection_test.go
Labels: lgtm, approved, ci-passed, size/XS

#783 test: add case to test inverted index on array field
  .github/workflows/nightly_ci.yml
  .github/workflows/test-ci.yaml
  test/testcases/index_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#788 enhance: Sync autoID insert/upsert test cases
  test/testcases/insert_test.go
  test/testcases/upsert_test.go
Labels: lgtm, approved, ci-passed, size/XS, test/ci

#787 feat: add support for partition key isolation property
  client/collection_test.go
  entity/collection_attr.go
  entity/collection_attr_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#790 test: Update BITMAP index cases
  test/common/utils.go
  test/testcases/groupby_search_test.go
  test/testcases/index_test.go
  test/testcases/query_test.go
Labels: lgtm, approved, ci-passed, size/M, test/ci

#794 enhance: Support specifying field schema to be cluster key
  entity/schema.go
  entity/schema_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M
