Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-02, with the labels that each got.

#663 enhance: Support hybrid search multiple vector fields
  client/ann_request.go
  client/client.go
  client/client_test.go
  client/data.go
  client/reranker.go
  examples/multivectors/main.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#664 Adding float16 and bfloat16 support
  client/collection.go
  entity/columns.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_vector_gen.go
  entity/columns_vector_gen_test.go
  entity/gen/gen.go
  entity/schema.go
  entity/schema_test.go
  examples/bfloat16/bfloat16.go
Labels: lgtm, approved, ci-passed, size/XL

#666 fix: Use latest error message for range_filter and radius check
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XS, test/ci

#665 enhance: Remove varchar column cannot use auto ID constraint
  client/collection.go
  client/collection_test.go
  test/testcases/collection_test.go
Labels: lgtm, approved, size/S, ci-passed

#667 enhance: [Cherry-Pick] Remove varchar column cannot use auto ID constraint (#665)
  client/collection.go
  client/collection_test.go
  test/testcases/collection_test.go
Labels: lgtm, approved, size/S, ci-passed

#668 enhance: Bump sdk & milvus-proto version to v2.3.6
  common/common.go
  go.mod
  go.sum
Labels: lgtm, approved, size/S, ci-passed
