Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-03, with the labels that each got.

#672 Add test cases for groupby search
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/gorupby_search_test.go
  test/testcases/index_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL, test/ci

#675 fix: Support retry on milvus errors and retry on ErrInconsistentRequery
  client/data.go
  client/util.go
  client/util_test.go
  merr/errors.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/L

#678 Fix: Adapt bf16/fp16 in row-based API
  entity/rows.go
  entity/rows_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#680 fix: Skip `TestSearchGroupByFloatDefault` case
  test/testcases/groupby_search_test.go
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement, test/ci

#682 enhance: Bump milvus-proto/go-api to v2.4.0-rc.1
  client/client_mock_test.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement

#683 fix: Rectify Weighted Rerank params
  client/reranker.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#684 enhance: Support Sparse Embedding
  client/insert.go
  entity/columns.go
  entity/columns_sparse.go
  entity/columns_sparse_test.go
  entity/schema.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#687 Update autoindex level check
  entity/genidx/genidx.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
Labels: lgtm, approved, size/S, ci-passed

#688 fix: Use corrent place holder type for fp16 vector
  client/insert.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS
