Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-05, with the labels that each got.

#741 enhance: Add api for describe database and alter database
  client/client.go
  client/client_mock_test.go
  client/database.go
  client/database_test.go
  client/options.go
  entity/collection_attr.go
  entity/database.go
  examples/database/database.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
  test/base/milvus_client.go
  test/testcases/database_test.go
Labels: lgtm, approved, ci-passed, size/L

#745 Fix the nil pointer panic caused by empty MetaCache in HybridSearch
  client/data.go
Labels: kind/bug, lgtm, approved, size/XS

#747 fix: Sync default partition number to 16
  test/common/utils.go
Labels: lgtm, approved, ci-passed, size/XS, test/ci

#748 enhance: Not pass empty group by field search param
  client/ann_request.go
  client/data.go
Labels: lgtm, approved, size/S, ci-passed, kind/improvement

#746 docs: add bump version 2.4.0 to readme
  README.md
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#749 enhance: Support query iterator
  client/client.go
  client/client_test.go
  client/data.go
  client/iterator.go
  client/options.go
  client/results.go
  entity/columns.go
  entity/columns_array.go
  entity/columns_array_gen.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_sparse.go
  entity/columns_varchar.go
  entity/columns_vector_gen.go
  examples/iterator/main.go
  test/testcases/insert_test.go
  test/testcases/load_release_test.go
  test/testcases/upsert_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL

#743 enhance: Add ListGrants and ListGrant RBAC methods
  client/client.go
  client/rbac.go
  client/rbac_test.go
  entity/rbac.go
Labels: lgtm, approved, ci-passed, size/L

#750 fix: Set dimension for Vector column `Slice` method
  entity/columns_vector_gen.go
Labels: lgtm, approved, ci-passed, size/XS

#751 fix: Set Slice start to Len if out-of-bound
  entity/columns_array.go
  entity/columns_array_gen.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_sparse.go
  entity/columns_varchar.go
  entity/columns_vector_gen.go
Labels: lgtm, approved, ci-passed, size/M

#752 enhance: Use collection cache in write operations
  client/data_test.go
  client/insert.go
  client/insert_test.go
  test/testcases/insert_test.go
  test/testcases/upsert_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#755 fix: Use lower case "and" operator in query iterator
  client/iterator.go
  test/testcases/index_test.go
Labels: lgtm, approved, ci-passed, size/XS
