Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-08, with the labels that each got.

#784 fix broken Grant() call
  client/client.go
  client/rbac.go
  client/rbac_test.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#795 Add the privilege and db name param for the operate privilege api
  client/client.go
  client/rbac.go
  client/rbac_test.go
  entity/rbac.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M

#797 enhance: Support search iterator in GoSDK
  client/client.go
  client/client_test.go
  client/iterator.go
  client/iterator_option.go
  client/results.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#796 test: verify bitmap cases
  test/testcases/index_test.go
  test/testcases/query_test.go
Labels: lgtm, approved, size/S, ci-passed, test/ci

#804 fix: invalid key for database level replica number props
  entity/collection_attr.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#807 enhance: Allow explicit dynamic JSON column as insert data
  client/insert.go
  entity/columns_json.go
  test/testcases/insert_test.go
  test/testcases/search_test.go
Labels: kind/enhancement, approved, size/M

#803 enhance: Add isL0,SkipDiskQuotaCheck option in Bulkinsert API
  client/options.go
Labels: lgtm, approved, size/S, ci-passed

#808 enhance: Add BackupRBAC/RestoreRBAC API to enable rbac backup
  client/client.go
  client/client_mock_test.go
  client/client_test.go
  client/rbac.go
  client/rbac_test.go
  entity/rbac.go
  examples/rbac/main.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/XL

#810 fix: Make `MetaCache` field of GrpcClient
  client/client_mock_test.go
  client/collection.go
  client/collection_test.go
  client/data.go
  client/database.go
  client/grpc_client.go
  client/insert.go
  client/iterator.go
  client/meta_cache.go
  client/options.go
  client/options_test.go
  client/row.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/L

#812 test: updata v2.2 nightly to v2.4 and add mmap scalar index cases
  .github/workflows/nightly_ci.yml
  test/testcases/index_test.go
  test/testcases/load_release_test.go
  test/testcases/main_test.go
Labels: lgtm, approved, ci-passed, size/L
