Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-10, with the labels that each got.

#829 feat: [2.4] Support unmarshal resultset into orm receiver (#827)
  client/data.go
  client/results.go
  client/results_test.go
  test/testcases/groupby_search_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/feature

#819 enhance: support null and default value in go sdk
  client/insert.go
  client/insert_test.go
  client/row_test.go
  entity/columns.go
  entity/columns_array.go
  entity/columns_array_gen.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_scalar_gen_test.go
  entity/columns_sparse.go
  entity/columns_varchar.go
  entity/columns_varchar_test.go
  entity/columns_vector_gen.go
  entity/gen/gen.go
  entity/genarray/gen_array.go
  entity/rows.go
  entity/schema.go
  entity/schema_test.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/XXL

#834 enhance: [2.4] Set default max send recv size
  client/config.go
  test/testcases/groupby_search_test.go
Labels: kind/enhancement, lgtm, approved, size/S, ci-passed

#835 enhance: [2.4] Move collection meta check to server side
  client/collection.go
  client/collection_test.go
  client/data.go
  client/data_test.go
  client/insert.go
  client/insert_test.go
  client/maintainance.go
  client/partition.go
  client/partition_test.go
  client/row.go
  client/row_test.go
  test/testcases/collection_test.go
  test/testcases/compact_test.go
  test/testcases/delete_test.go
  test/testcases/flush_test.go
  test/testcases/index_test.go
  test/testcases/iterator_test.go
  test/testcases/load_release_test.go
  test/testcases/resource_group_test.go
  test/testcases/ut.log
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#837 enhance: [2.4] Hide buggy search iterator interface
  client/client.go
Labels: lgtm, approved, ci-passed, size/XS

#838 enhance: [2.4] Expose GetIndexBuildProgress and bump version
  client/client.go
  client/index.go
  client/index_test.go
  common/common.go
  test/testcases/ut.log
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#840 fix: RestoreRBAC pass wrong role info of user
  client/rbac.go
  examples/rbac/main.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M
