Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-01, with the labels that each got.

#645 Add merr package to utilize milvus error
  client/client_mock_test.go
  common/common.go
  go.mod
  go.sum
  merr/errors.go
  merr/errors_test.go
  merr/utils.go
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/XXL, kind/improvement

#634 feat: support alter index
  client/client_mock_test.go
  client/index.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/M

#647 enhance: add nightly-ci for v2.3.x branch
  .github/workflows/nightly_ci.yml
Labels: kind/enhancement, lgtm, approved, ci-passed, size/M, kind/workflow

#651 enhance: [2.3] Remove `HasCollection` & `HasPartition` grpc call
  client/collection.go
  client/collection_test.go
  client/data.go
  client/data_test.go
  client/insert.go
  client/insert_test.go
  client/partition.go
  client/partition_test.go
  client/row.go
  client/row_test.go
  go.mod
  go.sum
  test/testcases/collection_test.go
  test/testcases/delete_test.go
  test/testcases/flush_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/load_release_test.go
  test/testcases/upsert_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#653 enhance: [cherry-pick] adjust workflow for merr & branches (#652)
  .github/mergify.yml
  .github/workflows/test-ci.yaml
Labels: kind/enhancement, lgtm, approved, size/S, ci-passed, kind/workflow

#648 enhance: [Cherry-pick] Add merr package to utilize milvus error (#645)
  .github/workflows/main.yml
  merr/errors.go
  merr/errors_test.go
  merr/utils.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL

#656 fix: [Cherry-pick] deduce AutoID from field info
  entity/schema.go
  entity/schema_test.go
  test/testcases/collection_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#658 enhance: Bump SDK & proto version to v2.3.5
  common/common.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/XS, kind/improvement

#659 test: case error msg change
  test/testcases/index_test.go
Labels: lgtm, approved, size/S, ci-passed, test/ci

#660 enhance: Suport GPUCagra & GPUBruteForce index type
  entity/index.go
  entity/index_cagra.go
  entity/index_test.go
Labels: lgtm, approved, ci-passed, size/L, kind/improvement

#661 Reapply "feat: support enabling mmap for collection (#632)" (#635)
  entity/collection_attr.go
Labels: kind/enhancement, lgtm, approved, size/S, ci-passed

#662 enhance: Support Search GroupBy feature
  client/client_mock_test.go
  client/data.go
  client/data_test.go
  client/options.go
  client/results.go
  examples/groupby/main.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/L
