Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-11, with the labels that each got.

#841 fix: Update error message and other behavior change
  client/data.go
  client/options.go
  client/options_test.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/delete_test.go
  test/testcases/groupby_search_test.go
  test/testcases/index_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XXL

#832 enhance: Set default max send recv size
  client/config.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XS

#839 fix: RestoreRBAC pass wrong role info of user
  client/rbac.go
  examples/rbac/main.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#844 enhance: [2.4] let level param accepts more types
  entity/genidx/genidx.go
  entity/indexes_search_param_gen.go
  entity/indexes_search_param_gen_test.go
Labels: lgtm, approved, ci-passed, size/M

#845 enhance: RBAC Custom Privilege Group API
  client/client.go
  client/client_mock_test.go
  client/rbac.go
  entity/rbac.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#847 enhance: RBAC grant v2 API
  client/client.go
  client/client_mock_test.go
  client/rbac.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: lgtm, approved, ci-passed, size/L

#848 fix: Remove uncompatible dep
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#850 test: update case for resource group declarative api
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/configure_test.go
  test/testcases/delete_test.go
  test/testcases/insert_test.go
  test/testcases/main_test.go
  test/testcases/option.go
  test/testcases/resource_group_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/L, test/ci

#849 enhance: [2.4] RBAC privielge group and grant v2 api
  client/client.go
  client/client_mock_test.go
  client/rbac.go
  entity/rbac.go
  go.mod
  go.sum
  mocks/MilvusServiceServer.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL

#816 feat: [2.4]add page retain order for range search
  entity/index.go
  entity/index_test.go
Labels: lgtm, approved, size/S, ci-passed, kind/feature
