Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-04, with the labels that each got.

#690 fix: Filter index info base on provided field name
  client/index.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#691 fix: Allow specify scalar index type
  entity/index.go
  entity/index_scalar.go
  entity/index_scalar_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#692 Fix: cannot find the latest amd image tag
  .github/workflows/nightly_ci.yml
  .github/workflows/test-ci.yaml
  client/ann_request.go
  test/testcases/groupby_search_test.go
  test/testcases/index_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/M, kind/improvement, kind/workflow

#685 Add test cases for fp16, bf16, hybrid search
  examples/multivectors/main.go
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/compact_test.go
  test/testcases/delete_test.go
  test/testcases/groupby_search_test.go
  test/testcases/hybrid_search_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/load_release_test.go
  test/testcases/main_test.go
  test/testcases/option.go
  test/testcases/partition_key_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
  test/testcases/upsert_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XXL

#700 fix: Build binary index on binary field and skip some cases
  test/common/utils.go
  test/testcases/delete_test.go
  test/testcases/index_test.go
  test/testcases/query_test.go
  test/testcases/resource_group_test.go
Labels: lgtm, approved, size/S, ci-passed, test/ci

#696 fix: Pass index type for Scalar indexes
  entity/index_scalar.go
  entity/index_scalar_test.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#703 Add test cases for Inverted scalar index
  test/testcases/groupby_search_test.go
  test/testcases/index_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L, test/ci

#706 Fix hybrid search case and response check
  test/common/response_check.go
  test/testcases/hybrid_search_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, size/S, ci-passed, test/ci

#711 enhance: Add collection `Properties` field for describe collection
  client/collection.go
  entity/collection.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XS

#712 fix: Use corrent idx when converting SparseVector
  entity/columns_sparse.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#713 fix: Pass extra params when creating Index
  client/index.go
Labels: lgtm, approved, ci-passed, size/XS

#717 Revert: "fix: Support retry on milvus errors and retry on ErrInconsistentRequery"
  client/data.go
  client/util.go
  client/util_test.go
  merr/errors.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#721 fix: Parse group by value for each rows of resultset
  client/data.go
  client/data_test.go
  client/results.go
  examples/groupby/main.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#722 enhance: Export `AlterIndex` API in client interface
  client/client.go
Labels: lgtm, approved, ci-passed, size/XS

#723 enhance: Add Sparse Index type enum
  entity/columns_sparse.go
  entity/index.go
  entity/index_sparse.go
  entity/index_sparse_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#719 Update some skipped cases
  go.mod
  go.sum
  test/common/utils.go
  test/testcases/collection_test.go
  test/testcases/compact_test.go
  test/testcases/configure_test.go
  test/testcases/groupby_search_test.go
  test/testcases/hybrid_search_test.go
  test/testcases/index_test.go
  test/testcases/load_release_test.go
  test/testcases/search_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#715 Add test cases for mmap
  test/base/milvus_client.go
  test/testcases/load_release_test.go
Labels: lgtm, approved, ci-passed, size/L, test/ci

#727 enhance: Support offset in hybrid search outer request
  client/ann_request.go
  client/client.go
  client/data.go
Labels: kind/enhancement, lgtm, approved, size/S, ci-passed

#729 fix: Use correct idx when Serialize Sparse vector
  entity/columns_sparse.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#720 Add test cases for sparse vector
  client/collection.go
  entity/rows.go
  test/common/response_check.go
  test/common/utils.go
  test/common/utils_client.go
  test/testcases/collection_test.go
  test/testcases/groupby_search_test.go
  test/testcases/hybrid_search_test.go
  test/testcases/index_test.go
  test/testcases/insert_test.go
  test/testcases/load_release_test.go
  test/testcases/main_test.go
  test/testcases/option.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XL

#732 fix: Return empty resultset for empty nq and related testcases
  client/data.go
  client/insert.go
  client/row.go
  entity/columns.go
  entity/columns_test.go
  entity/schema.go
  test/testcases/groupby_search_test.go
  test/testcases/search_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/L

#736 fix: Fix recent behavior change caused case failure
  test/testcases/delete_test.go
  test/testcases/search_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M, test/ci

#735 fix: Use correct index range for refect Slice method
  entity/rows.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#737 fix: Pass offset param in rerank params for HybridSearch
  client/data.go
  test/base/milvus_client.go
  test/common/utils.go
  test/testcases/hybrid_search_test.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M

#738 Fix resource group failed cases in nightly
  test/testcases/resource_group_test.go
Labels: lgtm, approved, size/S, ci-passed, test/ci

#697 enhance: Add Describe User methods
  client/client.go
  client/rbac.go
  client/rbac_test.go
  entity/rbac.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#739 fix: Make custom DialOption overwrite default ones
  client/config.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#740 enhance: Bump sdk & proto verison to v2.4.0
  .github/workflows/main.yml
  common/common.go
  go.mod
  go.sum
Labels: lgtm, approved, size/S, ci-passed, kind/improvement
