Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-12, with the labels that each got.

#853 test: fix case TestLoadEmptyPartitionName
  test/testcases/load_release_test.go
Labels: lgtm, approved, size/S, ci-passed, test/ci

#852 fix: optional db for grant/revoke v2
  client/client.go
  client/rbac.go
Labels: lgtm, approved, size/S, ci-passed

#854 test: fix nightly failed case
  test/common/utils.go
  test/testcases/index_test.go
  test/testcases/load_release_test.go
Labels: lgtm, approved, ci-passed, size/M, test/ci

#856 fix: [2.4] optional db for grant/revoke v2
  client/client.go
  client/rbac.go
Labels: kind/enhancement, lgtm, approved, size/S, ci-passed

#858 test: add case insert rows with autoID
  test/testcases/insert_test.go
Labels: lgtm, approved, ci-passed, size/M, test/ci

#859 test: add case insert rows with autoID
  test/testcases/groupby_search_test.go
  test/testcases/insert_test.go
Labels: lgtm, approved, ci-passed, size/M, test/ci

#860 enhance: support hints param
  client/ann_request.go
  client/data.go
  client/options.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/XS

#862 enhance: support recall in SearchResult
  client/data.go
  client/results.go
  go.mod
  go.sum
Labels: lgtm, approved, size/S, ci-passed

#863 enhance: [2.4] support recall in SearchResult
  client/data.go
  client/results.go
  go.mod
  go.sum
  test/testcases/load_release_test.go
Labels: lgtm, approved, size/S, ci-passed
