Repository milvus-io/milvus-sdk-go, pull requests merged in 2024-06, with the labels that each got.

#757 enhance: refine param name for AlterDatabase
  client/client.go
Labels: lgtm, approved, ci-passed, size/XS

#761 fix: Add parentheses for query iterator origin expr
  client/iterator.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#762 fix: Check batch size when initializing iterator
  client/iterator.go
Labels: kind/bug, lgtm, approved, ci-passed, size/XS

#764 fix: Check empty expr before compose iterator next batch
  client/iterator.go
Labels: kind/bug, lgtm, approved, size/S, ci-passed

#765 fix: Make FP16 & BF16 column use correct byte len when parsing
  client/results.go
  entity/columns.go
  entity/columns_array.go
  entity/columns_array_gen.go
  entity/columns_json.go
  entity/columns_scalar_gen.go
  entity/columns_sparse.go
  entity/columns_varchar.go
  entity/columns_vector_gen.go
Labels: lgtm, approved, ci-passed, size/L

#768 enhance: Support InMemory option for ListCollection
  client/client.go
  client/collection.go
  client/options.go
Labels: lgtm, approved, size/S, ci-passed

#766 Support CDC
  client/client.go
  client/insert.go
Labels: lgtm, approved, size/S, ci-passed

#760 feat: add test cases for query iterator
  entity/schema.go
  test/base/milvus_client.go
  test/common/response_check.go
  test/common/utils.go
  test/testcases/configure_test.go
  test/testcases/delete_test.go
  test/testcases/highlevel_test.go
  test/testcases/main_test.go
  test/testcases/query_test.go
  test/testcases/search_test.go
Labels: lgtm, approved, ci-passed, size/XL

#771 enhance: Bump sdk verison to v2.4.1
  common/common.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/XS

#733 enhance: add resource group declarative api
  client/client.go
  client/options.go
  client/options_test.go
  client/resource_group.go
  client/resource_group_test.go
  entity/resource_group.go
  examples/resourcegroup/resourcegroup.go
  test/testcases/resource_group_test.go
Labels: kind/enhancement, lgtm, approved, ci-passed, size/L

#773 fix: failed to collection error in examples
  examples/auth/auth.go
  examples/insert/insert.go
  examples/tls/tls.go
Labels: kind/bug, lgtm, approved, ci-passed, size/M
